apiVersion: v1
kind: ConfigMap
metadata:
  name: school-api-config
  namespace: school-api
data:
  node-env: "production"
  mongo-uri: "mongodb://admin:xY3zA5bC8dE0fG2hI4jK6lM8n9oP1q@mongo-service:27017/school_db?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: school-api-secret
  namespace: school-api
type: Opaque # default
stringData: 
  jwt-secret: "8fH2jK9mP4qR7sT1vW6xY3zA5bC8dE0fG2hI4jK6lM8n"  # if we use 'data' instead of 'stringData', we need to base64 encode the value
  mongo-root-username: "admin"
  mongo-root-password: "xY3zA5bC8dE0fG2hI4jK6lM8n9oP1q"