apiVersion: v1
kind: ConfigMap
metadata:
  name: school-api-config
  namespace: school-api
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb://admin:xY3zA5bC8dE0fG2hI4jK6lM8n9oP1q@mongo-service:27017/school_db?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: school-api-secret
  namespace: school-api
type: Opaque
stringData:
  # Change these values before deploying
  JWT_SECRET: "8fH2jK9mP4qR7sT1vW6xY3zA5bC8dE0fG2hI4jK6lM8n"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "xY3zA5bC8dE0fG2hI4jK6lM8n9oP1q"
