apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: school-api-ingress
  namespace: school-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public # Default class for MicroK8s
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: school-api-service
            port:
              number: 80